---
title: "RShiny Open Payment Analysis Code"
author: "Jonathan Harris"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# CMS Open Payment Dataset Analysis

#Setup DataFrames for Plots and RShiny
### Setup Program
```{r, message=FALSE, warning=FALSE}

#Clearout environment
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc()

#Load Packages
library(tidyverse)
library(dplyr)
library(ggplot2)
library(scales)
library(RColorBrewer)
library(broom)
library(ggalt)
library(tidyr)

#Download BBC Theme
if(!require(pacman))install.packages("pacman")
pacman::p_load('dplyr', 'tidyr', 'gapminder',
               'ggplot2',  'ggalt',
               'forcats', 'R.utils', 'png', 
               'grid', 'ggpubr', 'scales',
               'bbplot')
devtools::install_github('bbc/bbplot')

setwd("/Users/jonathanharris/Desktop/NYCDSA/projects/rshiny_proj")

```

### Import Datas
```{r data import}

#Import Specialty Descriptive Summary CSV
specialty_data = read_csv('DataSets/topspecialty_descriptive.csv')

#Import Product Descriptive Summary CSV
productdata = read_csv('DataSets/openpayment_products_descriptive.csv')

```

### Plot Specialty Descriptive Data
```{r specialty plot}

#Convert units for plot
specialties_data = specialty_data %>% arrange(desc(total_payments)) %>% head(15)
specialties_data$physician_specialty[14] = 'Thoracic Surgery'

#Plot
specialties_plot = ggplot(data = specialties_data,
                          aes(x = npayments, y = total_payments, color = physician_specialty)) + geom_point(aes(size = ndoctors)) +
  bbc_style() +
  labs(title = "Number and Total of Clincian Payments [log10], By Specialty",
       subtitle = "Notable differences in payment sum and count relationship",
       caption = "Data source: 2016 Open Payments, cms.gov") +
  geom_hline(yintercept = 0,
             size = 1,
             colour = "#333333") +
  theme(
    plot.margin = margin(1, 1 , 1, 1, "cm"),
    legend.position = 'right',
    legend.text = element_text(size = 10),
    legend.spacing.y = unit(.5, 'cm'),
    plot.title = element_text(size = 24),
    plot.subtitle = element_text(size = 16, face = "italic"),
    plot.caption = element_text(size = 6, hjust = 1)
    
  ) +
  scale_y_continuous(
    name = "US Dollars [log10]",
    trans = 'log10',
    label = unit_format(
      prefix = "$",
      unit = "M",
      scale = 1e-6
    )
  ) +
  scale_x_continuous(
    name = "Num. of Payments [log10]",
    trans = 'log10',
    breaks = c(.1e6, .3e6, 1e6, 3e6),
    labels = c("100k", "300k", "1M", "3M payments")
  ) +
  geom_label(
    aes(y = 498308026.13,	x = 4452173, label = "Internal Medicine"),
    hjust = 1.1,
    colour = "#555555",
    fill = "white",
    label.size = NA,
    family = "Helvetica",
    size = 3
  ) +
  geom_label(
    aes(y = 407526186.84,	x = 281374, label = "Orthopaedic Surgery"),
    hjust = 1.1,
    colour = "#555555",
    fill = "white",
    label.size = NA,
    family = "Helvetica",
    size = 3
  ) +
  geom_label(
    aes(y = 126804832.61,	x = 831908, label = "Psychiatry & Neurology"),
    hjust = 1.1,
    colour = "#555555",
    fill = "white",
    label.size = NA,
    family = "Helvetica",
    size = 3
  ) +
  geom_label(
    aes(y = 81691769.98,	x = 81212, label = "Neurological Surgery"),
    hjust = -.05,
    colour = "#555555",
    fill = "white",
    label.size = NA,
    family = "Helvetica",
    size = 3
  )

ggsave(
  'plots/openpayments_specialties.png',
  plot = specialties_plot,
  units = "in",
  height = 7,
  width = 12,
  dpi = 300
)

```

### Plot Product Type Descriptive Data
```{r product plot}

product_plot = productdata %>% group_by(product_type) %>% 
  summarise(var = sum(num_payment_per_total)) %>% 
  ggplot(data=., aes(x=reorder(product_type,-var), y=var, fill = product_type)) + geom_bar(stat='identity', position='dodge') +
  scale_fill_manual(values = c('#FAAB18' , '#1380A1', '#a13b0f')) +
  bbc_style() +
    scale_y_continuous(
    label = unit_format(accuracy = 1, unit = "M", scale = 1e-6)) +
  labs(title = "Number of Payments, By Product Type",
       subtitle = "Drug companies make overwhelming majority of all clinician payments",
       caption = "Data source: 2016 Open Payments, cms.gov") +
  geom_hline(yintercept = 0,
             size = 1,
             colour = "#333333") +
  geom_label(
    aes(label = format(
      round(var, 0), big.mark = ",", scientific = FALSE
    )),
    hjust = .5,
    vjust = 1,
    colour = "white",
    fill = NA,
    label.size = NA,
    family = "Helvetica",
    size = 5
  ) +
  theme(
    panel.grid.major.y = element_line(color = "#cbcbcb"),
    panel.grid.major.x = element_blank(),
    plot.margin = margin(1, 1, 1, 1, "cm"),
    legend.position = 'none',
        plot.title = element_text(size = 24),
    plot.subtitle = element_text(size = 16, face = "italic"),
    plot.caption = element_text(size = 6, hjust = 1)
  ) +
  scale_colour_manual(
    labels = function(x)
      paste0(" ", x, "  ")
  )

ggsave(
  'plots/openpayments_productplot.png',
  plot = product_plot ,
  units = "in",
  height = 7,
  width = 12,
  dpi = 300
)

```


